# Generated by Django 2.1.5 on 2019-01-17 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название Работы')),
                ('text', models.TextField()),
                ('category', models.CharField(choices=[('TO DO', 'TO DO'), ('In progress', 'In progress'), ('Done', 'Done')], default='TO DO', max_length=6)),
            ],
            options={
                'verbose_name': 'Работа',
                'verbose_name_plural': 'Работы',
            },
        ),
    ]
