# Generated by Django 2.1.5 on 2019-01-19 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoTest', '0004_auto_20190117_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='category',
            field=models.CharField(choices=[('to do', 'to do'), ('in progress', 'in progress'), ('done', 'done')], default='to do', max_length=15),
        ),
    ]
